# Generated by Django 5.0.1 on 2024-01-25 14:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть введен в формате: '+79999999999'", regex='^(\\+7)(\\d{10})$')])),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
