# Generated by Django 5.0.1 on 2024-02-01 11:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть введен в формате: '+79999999999'", regex='^(\\+7)(\\d{10})$')]),
        ),
    ]
