# Generated by Django 5.0.1 on 2024-02-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_lead_phone_number_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='qq', max_length=200),
            preserve_default=False,
        ),
    ]
