# Generated by Django 5.0.1 on 2024-02-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_task_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('1', 'Создана заявка'), ('2', 'Купил'), ('3', 'Отказ')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
