# Generated by Django 5.0.1 on 2024-02-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_alter_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('1', 'Создана заявка'), ('2', 'Купил'), ('3', 'Отказ')], default='2', max_length=1),
        ),
    ]
