# Generated by Django 5.0.1 on 2024-03-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_alter_deal_date_of_deal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-pk']},
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('1', 'Яндекс Директ'), ('2', 'Вконтакте'), ('3', 'Инстаграм'), ('4', 'SEO'), ('5', 'Посоветовали'), ('6', 'Прочее')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
