# Generated by Django 5.0.1 on 2024-04-04 14:04

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_alter_lead_options_lead_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_of_creation',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='task_date',
            field=models.DateField(default=datetime.date(2024, 4, 4)),
        ),
    ]
