# Generated by Django 5.0.1 on 2024-04-17 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_alter_deal_options_alter_lead_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='date_of_deal',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_date',
            field=models.DateField(default=datetime.date(2024, 4, 17)),
        ),
    ]
