# Generated by Django 5.0.1 on 2024-04-17 09:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_alter_deal_date_of_deal_alter_task_task_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
