# Generated by Django 5.0.1 on 2024-04-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_alter_task_task_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['task_date']},
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('', '----------'), ('Яндекс Директ', 'Яндекс Директ'), ('Вконтакте', 'Вконтакте'), ('Инстаграм', 'Инстаграм'), ('SEO', 'SEO'), ('Посоветовали', 'Посоветовали'), ('Прочее', 'Прочее')], max_length=20),
        ),
    ]
