# Generated by Django 5.0.1 on 2024-04-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0017_alter_task_options_alter_lead_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
