# Generated by Django 5.0.1 on 2024-04-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0019_alter_deal_date_of_deal_alter_lead_date_of_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='date_of_deal',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='date_of_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
